### ISSUE TITLE
Indicate how many slides there are

### ISSUE THREAD

**Issue by r12a** [w3c/presentation-viewer#38]
When watching a video in the 'kiosk' version, i sometimes found myself wondering how close i was to the end of the presentation.  I can find out by mousing over the video itself, but it would be nice to see at a glance.  This could be done by changing "Slide 3" below the video to something like "Slide 3 / 10".

Not a major issue, but would be nice.

**Comment by bert-github** [comment]
I agree it's useful, even though slides don't take equal time. 

And it was an easy change.

I made it "Slide 3 of 10" instead of "Slide 3 / 10", so that the speech synthesizer says "three of ten" rather than "three ten".

A slight worry is that speaking two extra words takes more time and thus makes hearing the video a bit harder.
